language: node_js
sudo: true
dist: trusty
cache:
  yarn: true
  directories:
  - node_modules
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
branches:
  only:
  - master
stages:
  - validation
  - test
  - deploy
jobs:
  include:
    - stage: validation
      script: npm run lint
    - stage: validation
      script: npm run test:e2e
    - stage: deploy
      script: skip
      deploy:
        provider: heroku
        api_key: $HEROKU_AUTH_TOKEN
        app: ci-workshop-client
