version: 2
jobs:
  build:
    lint:
    # specify the version you desire here
    - image: circleci/node:8.12.0

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/ci-client

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      # run tests!
      - run: yarn lint

      - persist_to_workspace:
          root: ~/ci-client
          paths:
            - node_modules

workflows:
  version: 2
  ci-client:
    jobs:
      - lint:
          filters:
            branches:
              only: master
