version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.12.0

    working_directory: ~/ci-client

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      # run tests!
      - run: yarn lint

      - persist_to_workspace:
          root: ~/ci-client
          paths:
            - node_modules
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  ci-client:
    jobs:
      - lint:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only: master
